package frc.robot.subsystems;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;

import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.LimelightHelpers;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class DriveSubsystem extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    //Pose Publishers so the robot pose appears in AdvantageScope
    StructPublisher<Pose2d> currentPosePublisher = NetworkTableInstance.getDefault()
        .getStructTopic("Robot Pose", Pose2d.struct).publish();
    StructPublisher<Pose2d> targetPosePublisher = NetworkTableInstance.getDefault()
        .getStructTopic("Target Pose", Pose2d.struct).publish();

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public DriveSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }


    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        //Update robot position with the limelight
        updatePoseWithLimelight("limelight");

        //Updates the robot pose in advantagescope
        currentPosePublisher.set(getCurrentPose());
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    
    //////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////// Info Getters //////////////////////////////////
    //////////////////////////////////////////////////////////////////////////////////
    
    public Pose2d getCurrentPose() {
        return this.getState().Pose;
    }

    public double getCurrentSpeed() {
        return Math.sqrt(Math.pow(this.getState().Speeds.vxMetersPerSecond, 2) + Math.pow(this.getState().Speeds.vyMetersPerSecond, 2));
    }

    //////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////// Driving Controls ////////////////////////////////
    //////////////////////////////////////////////////////////////////////////////////

    SwerveRequest.FieldCentric fieldCentricRequest = new SwerveRequest.FieldCentric();
    SwerveRequest.RobotCentric robotCentricRequest = new SwerveRequest.RobotCentric();
    SwerveRequest.SwerveDriveBrake brakeRequest = new SwerveRequest.SwerveDriveBrake();
    double maxJoystickSpeed = 3, maxJoystickRotSpeed = Math.PI;

    public void setFieldCentricState(double leftX, double leftY, double rightX) {
        this.setControl(
            fieldCentricRequest
                .withVelocityX(leftY * maxJoystickSpeed)
                .withVelocityY(leftX * maxJoystickSpeed)
                .withRotationalRate(rightX * maxJoystickRotSpeed)
        );
    }

    public void setRobotCentricState(double leftX, double leftY, double rightX) {
        this.setControl(
            robotCentricRequest
                .withVelocityX(leftX * maxJoystickSpeed)
                .withVelocityY(leftY * maxJoystickSpeed)
                .withRotationalRate(rightX * maxJoystickRotSpeed)
        );
    }

    public void setBrakeState() {
        //Turns the swerve into an X formation
        this.setControl(brakeRequest);
    }

    public void setMaxJoystickSpeed(double maxSpeed) {
        maxJoystickSpeed = maxSpeed;
    }

    ///////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////// Drive To Pose //////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////

    SwerveRequest.FieldCentricFacingAngle driveToPoseRequest = new SwerveRequest.FieldCentricFacingAngle()
        .withMaxAbsRotationalRate(Math.PI * 2)
        .withHeadingPID(7, 0, 0)
        .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance); //Makes the field centric of drive to pose the same for red and blue

    double maxPositionalSpeed = 3, maxPositionalRotSpeed = Math.PI;
    double posKP = 20, posKI = 0, posKD = 0.01;
    ProfiledPIDController xPosController = new ProfiledPIDController(posKP, posKI, posKD, new TrapezoidProfile.Constraints(maxPositionalSpeed, 3));
    ProfiledPIDController yPosController = new ProfiledPIDController(posKP, posKI, posKD, new TrapezoidProfile.Constraints(maxPositionalSpeed, 3));

    Pose2d positionalTargetPose = Pose2d.kZero;

    public boolean isDriveToPoseAtPosition(double tolerance) {
        return Math.sqrt(Math.pow(positionalTargetPose.getX() - getCurrentPose().getX(), 2) + Math.pow(positionalTargetPose.getY() - getCurrentPose().getY(), 2)) < tolerance;
    }

    public void setTargetPose(Pose2d target) {
        positionalTargetPose = target;
    }

    public void setDriveToPoseState() {
        //Updates poses in AdvantageScope
        //Current Pose here for simulation, could be removed if issue fixed
        currentPosePublisher.set(getCurrentPose());
        targetPosePublisher.set(positionalTargetPose);

        //Set the target of the robot to the target pose
        xPosController.setGoal(positionalTargetPose.getX());
        yPosController.setGoal(positionalTargetPose.getY());

        //Determine velocity of drivetrain
        double xSpeed = xPosController.calculate(getCurrentPose().getX());
        double ySpeed = yPosController.calculate(getCurrentPose().getY());

        //Apply speeds to robot
        this.setControl(driveToPoseRequest
            .withVelocityX(xSpeed)
            .withVelocityY(ySpeed)
            .withTargetDirection(positionalTargetPose.getRotation())
        );
    }

    ///////////////////////////////////////////////////////////////////////////////////
    //////////////////////////////// Limelight Methods ////////////////////////////////
    ///////////////////////////////////////////////////////////////////////////////////

    public void updatePoseWithLimelight(String limelightName) {
        boolean updateVision = true;
        
        LimelightHelpers.SetRobotOrientation(limelightName, getCurrentPose().getRotation().getDegrees(), 0, 0, 0, 0, 0);
        LimelightHelpers.PoseEstimate mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue(limelightName);
        LimelightHelpers.PoseEstimate mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(limelightName);

        Rotation2d currentOrientation = null;

        if(mt1 != null) {
          
            if(mt1.tagCount == 1 && mt1.rawFiducials.length == 1) {
                if(mt1.rawFiducials[0].ambiguity > .7)
                {
                    updateVision = false;
                }
                if(mt1.rawFiducials[0].distToCamera > 3)
                {
                    updateVision = false;
                }
            }
            if(mt1.tagCount == 0) {
                updateVision = false;
            }
            if(updateVision) {
                currentOrientation = mt1.pose.getRotation();
            }
        }

        if (currentOrientation == null) {
            currentOrientation = getCurrentPose().getRotation();
        }

        
        
        if(mt2 != null && mt2.tagCount != 0 &&Math.abs(getPigeon2().getAngularVelocityZWorld().getValueAsDouble()) > 720) { // if our angular velocity is greater than 720 degrees per second, ignore vision updates
          setVisionMeasurementStdDevs(VecBuilder.fill(0.15,0.15,Math.toRadians(10))); 
                addVisionMeasurement(
                    new Pose2d(mt2.pose.getTranslation(), currentOrientation),
                    Utils.fpgaToCurrentTime(mt2.timestampSeconds));
        }

    }
}
